#+TITLE: About MAAS
#+AUTHOR: Bill Wear
#+EMAIL: wowear@protonmail.com
#+HTML_HEAD:     <link rel="stylesheet" href="https://stormrider.io/css/stylesheet.css" type="text/css">

| Getting started | Advanced activities |
|-----------------+---------------------|
| [[https://stormrider.io/maas-section.html][Intro]]           | [[https://stormrider.io/maas-cli-6.html][jq Tricks]]           |
| [[https://stormrider.io/maas-cli-1.html][Install]]         | [[https://stormrider.io/maas-cli-7.html][SSH/SCP]]             |
| [[https://stormrider.io/maas-cli-2.html][Config]]          | [[https://stormrider.io/maas-cli-8.html][More jq Tricks]]      |
| [[https://stormrider.io/maas-cli-3.html][DHCP]]            | [[https://stormrider.io/maas-cli-9.html][MAAS CLI Walkthru]]   |
| [[https://stormrider.io/maas-cli-4.html][Commissioning]]   |                     |
| [[https://stormrider.io/maas-cli-5.html][Deployment]]      |                     |
-------

From the MAAS documentation:
#+BEGIN_QUOTE
"MAAS is an open-source tool that lets you create a data centre from
bare-metal servers. You can discover, commission, deploy, and
dynamically reconfigure a large network of individual units. MAAS
converts your hardware investment into a cohesive, flexible,
distributed data centre, with a minimum of time and effort."
#+END_QUOTE

From 9-6 every weekday, I write docs and create new doc tools for the
[[https://maas.io][MAAS]] product, and [[https://canonical.com][Canonical]] pays me for it. That's probably the best
way to describe what it's like working on an open-source product for a
larger company that develops them.  I like what I do, and I do it
whenever I can afford it.  Canonical makes it very easy for me to
afford it, so it's natural to share the benefit of my hobbies with
them whenever I can.

MAAS has a really nice UI that's super-easy to use.  It also has at
least two CLIs and a REST API (which backs the CLIs). I've made an
informal hobby of trying to use MAAS via the command-line only.  It's
sort of a challenge to try to see how much I can do, and how much I
can document, using just the MAAS CLI.
